---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:

    # TODO: Developer must implement and populate 'server' variable

    - name: Create instance config
      when: server.changed | default(false) | bool  # noqa no-handler
      block:
        - name: Populate instance config dict  # noqa jinja
          ansible.builtin.set_fact:
            instance_conf_dict: {
              'instance': "{{ }}",
              'address': "{{ }}",
              'user': "{{ }}",
              'port': "{{ }}",
              'identity_file': "{{ }}", }
          with_items: "{{ server.results }}"
          register: instance_config_dict

        - name: Convert instance config dict to a list
          ansible.builtin.set_fact:
            instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

        - name: Create fish config dir
          ansible.builtin.file:
            path: "{{ lookup('env', 'HOME') }}/.config/fish"
            state: directory
            mode: '0755'

        - name: Create fish config file
          ansible.builtin.copy:
            dest: "{{ lookup('env', 'HOME') }}/.config/fish/config.fish"
            content: |
              if status is-interactive
                # Commands to run in interactive sessions can go here
              end
            owner: "{{ ansible_user_id }}"
            group: "{{ ansible_user_gid }}"
            mode: '0644'

        - name: Create .zshrc file
          ansible.builtin.copy:
            dest: "{{ lookup('env', 'HOME') }}/.zshrc"
            content: |
              bindkey -e
              # Lines configured by zsh
            owner: "{{ ansible_user_id }}"
            group: "{{ ansible_user_gid }}"
            mode: '0644'

        - name: Dump instance config
          ansible.builtin.copy:
            content: |
              # Molecule managed

              {{ instance_conf | to_json | from_json | to_yaml }}
            dest: "{{ molecule_instance_config }}"
            mode: "0600"
